"""empty message

Revision ID: 49e4a87b398c
Revises: 8505153e6045
Create Date: 2020-10-08 22:15:38.023225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e4a87b398c'
down_revision = '8505153e6045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('RECEIVE', 'RELEASE', 'SELL', name='bookactionname'), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_action')
    # ### end Alembic commands ###
