# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Check code with Pylint
      run: |
        pylint app/ tests/
    - name: Check code with Pycodestyle
      run: |
        pycodestyle app/ tests/
    - name: Check types with Mypy
      run: |
        mypy app/
    - name: Test with Pytest
      run: |
        pytest -m "not webtest"
